# Generated by Django 4.2.16 on 2024-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='question_hot_idx',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='likes_count',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='likes_count',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='answerlike',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default='like', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlike',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default='like', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-rating', '-created_at'], name='question_hot_idx'),
        ),
    ]
