# Generated by Django 5.1.3 on 2024-11-13 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_answer_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-created_at'], name='answer_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question_id'], name='answer_question_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='question_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='app_tag_name_c400d7_idx'),
        ),
    ]
