# Generated by Django 5.1.3 on 2024-11-13 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_answer_created_at_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_count_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likes_count_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-likes_count_cache', '-created_at'], name='question_hot_idx'),
        ),
    ]
