# Generated by Django 5.1.3 on 2024-11-13 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_answers_count_cache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='answer_question_idx',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='answer_created_at_asc_idx'),
        ),
    ]
