# Generated by Django 5.1.3 on 2024-11-13 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_answer_answer_question_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='question_hot_idx',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answers_count_cache',
            new_name='answers_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='likes_count_cache',
            new_name='likes_count',
        ),
        migrations.AddField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-likes_count', '-created_at'], name='question_hot_idx'),
        ),
    ]
